# Generated by Django 5.1.5 on 2025-01-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('extension', models.CharField(max_length=12)),
                ('last_time_modified', models.DateField()),
                ('references', models.ManyToManyField(to='core.file')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
            ],
        ),
    ]
