# Generated by Django 5.1.5 on 2025-02-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
    ]
