# Generated by Django 5.1.5 on 2025-02-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_user_main_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionhandler',
            old_name='access_list',
            new_name='access_lists',
        ),
        migrations.AddField(
            model_name='accesslist',
            name='groups',
            field=models.ManyToManyField(related_name='access_lists', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='accesslist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
