# Generated by Django 5.1.5 on 2025-01-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_file_folder_folder_permissions_alter_folder_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='Directory',
        ),
    ]
