# Generated by Django 5.1.5 on 2025-02-06 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_access_list_permissionhandler_access_lists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
