# Generated by Django 5.1.5 on 2025-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_folder_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
