# Generated by Django 5.1.5 on 2025-02-03 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_directory_parent_alter_file_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='file',
            name='references',
        ),
        migrations.CreateModel(
            name='AccessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dir_access_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('extension', models.CharField(max_length=12)),
                ('last_time_modified', models.DateField()),
                ('references', models.ManyToManyField(to='core.archive')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('permissionhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.permissionhandler')),
                ('name', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=256)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.section')),
            ],
            bases=('core.permissionhandler',),
        ),
        migrations.AddField(
            model_name='permissionhandler',
            name='access_list',
            field=models.ManyToManyField(to='core.accesslist'),
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='archive',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.section'),
        ),
    ]
