# Generated by Django 5.1.5 on 2025-02-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_section_parent_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.section'),
        ),
    ]
