# Generated by Django 5.1.5 on 2025-02-18 10:20

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_archive_file_alter_user_main_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(default=None, upload_to=pathlib.PurePosixPath('/home/elias/Desktop/Source/work/la-wiki/portal/core/uploads')),
        ),
    ]
