# Generated by Django 5.1.5 on 2025-02-18 10:23

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_archive_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(default=None, upload_to=pathlib.PurePosixPath('/home/elias/Desktop/Source/work/la-wiki/portal/uploads')),
        ),
    ]
