services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=elasticsearch
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.verification_mode=none
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -u elastic:changeablepassword1357 http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
      
  fscrawler:
    image: dadoonet/fscrawler:${FSCRAWLER_VERSION}
    container_name: fscrawler
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - FS_JAVA_OPTS=${FS_JAVA_OPTS}
    volumes:
      - ../../test-documents/src/main/resources/documents/:/tmp/es:ro
      - ./config:/root/.fscrawler
      - ./logs:/usr/share/fscrawler/logs
      - ./external:/usr/share/fscrawler/external
    ports:
      - ${FSCRAWLER_PORT}:8080
    command: idx --restart --rest

  database:
    image: mariadb:11.6.2-noble
    networks:
      - muniwiki
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ${DB_NAME}

  admin:
    image: adminer
    ports:
      - "${DB_ADMIN_PORT}:8080"
    networks:
      - muniwiki

volumes:
  dbvol:
  certs:
    driver: local
  esdata:
    driver: local

networks:
  muniwiki:
    driver: bridge

