# Generated by Django 5.1.5 on 2025-01-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('extension', models.CharField(max_length=12)),
                ('last_time_modified', models.DateField()),
                ('references', models.ManyToManyField(to='wikiapp.file')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiapp.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiapp.menu')),
            ],
        ),
    ]
