# Generated by Django 5.1.5 on 2025-02-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reverse_view_url', models.CharField(default='wikiapp:home', max_length=200)),
                ('groups', models.ManyToManyField(to='auth.group')),
            ],
        ),
    ]
