# Generated by Django 5.1.5 on 2025-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0002_alter_menu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='reverse_view_url',
            field=models.CharField(default='wikiapp:home', max_length=200),
        ),
    ]
