# Generated by Django 5.1.5 on 2025-01-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0003_menu_reverse_view_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
